version: "3"

services:
  api:
    build: .
    environment:
      - REDIS_URI=redis:6379
      - PORT=:4000
      - DOMAIN=localhost:4000
      - API_QUOTA=10
    ports:
      - "4000:4000"
    depends_on:
      - redis
  redis:
    image: redis

